Repository TykTechnologies/mintlify-poc, pull requests merged in 2025-10, with the labels that each got.

#718 Script for Adding Seo Canonical URLs
  .github/workflows/deploy-docs.yml
  scripts/add-canonical-urls/index.js
  scripts/add-canonical-urls/test.js
Labels: release-5.8, release-5.9, Review effort 2/5

#724 Fix seo script
  .github/workflows/deploy-docs.yml
  scripts/add-canonical-urls/index.js
  scripts/add-canonical-urls/index.py
  scripts/add-canonical-urls/test.js
Labels: release-5.8, production, release-5.9

#743 🤖 Auto-merge documentation from branches
  5.8/api-management/automations/operator.mdx
  5.8/portal/install.mdx
  snippets/5.8/AIStudioCards.mdx
  snippets/5.8/Badge.mdx
  snippets/5.8/FeatureCards.mdx
  snippets/5.8/GitHubStarButton.mdx
  snippets/5.8/RedisVersions.mdx
  snippets/5.8/UIExampleCards.mdx
  snippets/5.9/AIStudioCards.mdx
  snippets/5.9/Badge.mdx
  snippets/5.9/FeatureCards.mdx
  snippets/5.9/GitHubStarButton.mdx
  snippets/5.9/UIExampleCards.mdx
  snippets/nightly/AIStudioCards.mdx
  snippets/nightly/Badge.mdx
  snippets/nightly/FeatureCards.mdx
  snippets/nightly/GitHubStarButton.mdx
  snippets/nightly/RedisVersions.mdx
  snippets/nightly/UIExampleCards.mdx
Labels: documentation, auto-deployment, automated, Review effort 2/5

#744 Add Copy Page
  docs.json
Labels: release-5.8, release-5.9, Review effort 1/5

#750 Sync Main with Master
  ai-management/ai-studio/deployment-k8s.mdx
  ai-management/mcps/api-to-mcp.mdx
  ai-management/mcps/overview.mdx
  ai-management/mcps/tyk-docs-mcp.mdx
  api-management/api-versioning.mdx
  api-management/dashboard-configuration.mdx
  api-management/gateway-config-tyk-classic.mdx
  api-management/logs-metrics.mdx
  api-management/manage-apis/deploy-apis/deploy-apis-overview.mdx
  api-management/plugins/golang.mdx
  api-management/plugins/javascript.mdx
  api-management/plugins/overview.mdx
  api-management/plugins/rich-plugins.mdx
  api-management/rate-limit.mdx
  api-management/request-quotas.mdx
  api-management/request-throttling.mdx
  api-management/response-caching.mdx
  api-management/traffic-transformation/allow-list.mdx
  api-management/traffic-transformation/block-list.mdx
  api-management/traffic-transformation/do-not-track.mdx
  api-management/traffic-transformation/ignore-authentication.mdx
  api-management/traffic-transformation/internal-endpoint.mdx
  api-management/traffic-transformation/mock-response.mdx
  api-management/traffic-transformation/request-body.mdx
  api-management/traffic-transformation/request-headers.mdx
  api-management/traffic-transformation/request-method.mdx
  api-management/traffic-transformation/request-size-limits.mdx
  api-management/traffic-transformation/request-validation.mdx
  api-management/traffic-transformation/response-body.mdx
  api-management/traffic-transformation/response-headers.mdx
  api-management/traffic-transformation/virtual-endpoints.mdx
  api-management/troubleshooting-debugging.mdx
  api-management/tyk-pump.mdx
  developer-support/documentation-projects/inclusive-naming.mdx
  developer-support/release-notes/cloud.mdx
  developer-support/release-notes/dashboard.mdx
  developer-support/release-notes/gateway.mdx
  developer-support/release-notes/helm-chart.mdx
  developer-support/release-notes/mdcb.mdx
  developer-support/release-notes/operator.mdx
  developer-support/release-notes/overview.mdx
  developer-support/release-notes/portal.mdx
  developer-support/release-notes/pump.mdx
  developer-support/release-notes/sync.mdx
  developer-support/release-notes/tib.mdx
  developer-support/release-types/fips-release.mdx
  developer-support/release-types/long-term-support.mdx
  developer-support/upgrading.mdx
  portal/install.mdx
  product-stack/tyk-charts/tyk-control-plane-chart.mdx
  product-stack/tyk-charts/tyk-stack-chart.mdx
  product-stack/tyk-sync/installing-tyk-sync.mdx
  snippets/tyk-gateway-features-include.mdx
  snippets/x-tyk-gateway.mdx
  transform-traffic/url-rewriting.mdx
  tyk-cloud/telemetry.mdx
  tyk-developer-portal/tyk-portal-classic/customise/custom-developer-portal.mdx
  tyk-self-managed/install.mdx
  tyk-stack/tyk-operator/create-an-api.mdx
Labels: Review effort 2/5

#753 Sync with 5.8
  ai-management/ai-studio/deployment-k8s.mdx
  ai-management/mcps/api-to-mcp.mdx
  ai-management/mcps/overview.mdx
  ai-management/mcps/tyk-docs-mcp.mdx
  api-management/api-versioning.mdx
  api-management/automations/operator.mdx
  api-management/dashboard-configuration.mdx
  api-management/gateway-config-tyk-classic.mdx
  api-management/logs-metrics.mdx
  api-management/manage-apis/deploy-apis/deploy-apis-overview.mdx
  api-management/plugins/golang.mdx
  api-management/plugins/javascript.mdx
  api-management/plugins/overview.mdx
  api-management/plugins/rich-plugins.mdx
  api-management/rate-limit.mdx
  api-management/request-quotas.mdx
  api-management/request-throttling.mdx
  api-management/response-caching.mdx
  api-management/traffic-transformation/allow-list.mdx
  api-management/traffic-transformation/block-list.mdx
  api-management/traffic-transformation/do-not-track.mdx
  api-management/traffic-transformation/ignore-authentication.mdx
  api-management/traffic-transformation/internal-endpoint.mdx
  api-management/traffic-transformation/mock-response.mdx
  api-management/traffic-transformation/request-body.mdx
  api-management/traffic-transformation/request-headers.mdx
  api-management/traffic-transformation/request-method.mdx
  api-management/traffic-transformation/request-size-limits.mdx
  api-management/traffic-transformation/request-validation.mdx
  api-management/traffic-transformation/response-body.mdx
  api-management/traffic-transformation/response-headers.mdx
  api-management/traffic-transformation/virtual-endpoints.mdx
  api-management/troubleshooting-debugging.mdx
  developer-support/documentation-projects/inclusive-naming.mdx
  developer-support/release-notes/cloud.mdx
  developer-support/release-notes/dashboard.mdx
  developer-support/release-notes/gateway.mdx
  developer-support/release-notes/helm-chart.mdx
  developer-support/release-notes/mdcb.mdx
  developer-support/release-notes/operator.mdx
  developer-support/release-notes/overview.mdx
  developer-support/release-notes/portal.mdx
  developer-support/release-notes/pump.mdx
  developer-support/release-notes/sync.mdx
  developer-support/release-notes/tib.mdx
  developer-support/release-types/fips-release.mdx
  developer-support/release-types/long-term-support.mdx
  developer-support/upgrading.mdx
  portal/install.mdx
  product-stack/tyk-charts/tyk-control-plane-chart.mdx
  product-stack/tyk-charts/tyk-stack-chart.mdx
  product-stack/tyk-sync/installing-tyk-sync.mdx
  snippets/tyk-gateway-features-include.mdx
  snippets/x-tyk-gateway.mdx
  transform-traffic/url-rewriting.mdx
  tyk-cloud/telemetry.mdx
  tyk-developer-portal/tyk-portal-classic/customise/custom-developer-portal.mdx
  tyk-self-managed/install.mdx
  tyk-stack/tyk-operator/create-an-api.mdx
Labels: Review effort 3/5

#707 Add Collapsible/Expandable Side Nav (TOC)
  toc.css
  toc.js
Labels: Review effort 2/5
