Repository TykTechnologies/mintlify-poc, pull requests merged in 2025-09, with the labels that each got.

#659 JSON LD structured data
  structured-data.js
Labels: Review effort 2/5

#696 🤖 Auto-merge documentation from branches
  nightly/structured-data.js
Labels: documentation, auto-deployment, automated

#684 Fixed Swagger API not Rendering
  docs.json
  swagger/ai-studio-swagger.yml
  swagger/dashboard-admin-swagger.yml
  swagger/dashboard-swagger.yml
  swagger/enterprise-developer-portal-swagger.yaml
  swagger/gateway-swagger.yml
  swagger/mdcb-swagger.yml
Labels: release-5.8, release-5.9, Review effort 2/5

#706 🤖 Auto-merge documentation from branches
  nightly/developer-support/inclusive-naming-policy.mdx
  nightly/portal/api-consumer/invite-codes.mdx
  nightly/product-stack/tyk-enterprise-developer-portal/api-documentation/list-of-endpoints/portal-1.13.0-list-of-endpoints.mdx
  nightly/tyk-developer-portal/tyk-enterprise-developer-portal/api-consumer-portal/access-api-product.mdx
  nightly/tyk-developer-portal/tyk-portal-classic/streams.mdx
  nightly/tyk-stack/tyk-developer-portal/enterprise-developer-portal/api-access/manage-apps-credentials.mdx
  nightly/tyk-stack/tyk-developer-portal/enterprise-developer-portal/getting-started-with-enterprise-portal/manage-get-started-guides-for-api-products.mdx
  nightly/tyk-stack/tyk-developer-portal/enterprise-developer-portal/managing-access/manage-api-consumers.mdx
  nightly/ui-examples/feature-cards.mdx
  nightly/ui-examples/test-pill-label-security.mdx
  nightly/ui-examples/test-pill-label.mdx
  nightly/ui-examples/youtube-video-embed.mdx
Labels: documentation, auto-deployment, automated
